basic.forever(function () {
    pins.digitalWritePin(DigitalPin.P8, 0)
    pins.digitalWritePin(DigitalPin.P12, 0)
    pins.analogWritePin(AnalogPin.P0, 800)
    pins.analogWritePin(AnalogPin.P1, 800)
    basic.pause(2000)
    pins.analogWritePin(AnalogPin.P0, 800)
    pins.analogWritePin(AnalogPin.P1, 400)
    basic.pause(2000)
    pins.analogWritePin(AnalogPin.P0, 800)
    pins.analogWritePin(AnalogPin.P1, 800)
    basic.pause(2000)
    pins.analogWritePin(AnalogPin.P0, 0)
    pins.analogWritePin(AnalogPin.P1, 800)
    basic.pause(2000)
    pins.analogWritePin(AnalogPin.P0, 0)
    pins.analogWritePin(AnalogPin.P1, 0)
    basic.pause(2000)
})
